travis:
  secure:
    BINSTAR_TOKEN: YntGpU1P6wNl0n16Ik2zwq1xZojfSTmdMVwan/J5VqHJiyZ9tlvuTs8Y6A7kYyBweXgCtYfInPPmtDfSRcrcgfcTXSMvvTZB78Kv8UujB9jKAtIa69kgotmBdxWfBAWfdRW4A/eAkV/9KVwtENYNyEhcy/VixpRqoY476cM0nTvooR/0lKf7wgYigakTYrbNOX8pmd8bVHB7S7asPedOXq00wHh0JDwghwVZ4jD3CoRfb8FiPHTMYIju/hTcuWKBxd0gSVwgWDL4Ikow0/W00hvbotvRam3ZJOTh7mud4VcADEwAntTG3txreBT8xZL7HRLREx6+ewQfSD6eQOmnJuNKjfAh4fCxGa7ksBYy5qaAX8t2dYYGHHpWycIKLc4OeEI0gNb4L52L8J/DRarjetAvupLc1nXWqw5vIbuXBr/R0DOBcuWi1PV8u9aepZ9e7oLaEHdKy75zHceeLcgD9zVoYVLh2cBCfSs32sEhgbiql8eIgW834igKFYZG7YyRIdpBDsV3Ao7QsJDrMHsRF0CLs68/Hy2GxPgNnOVna7G5eIA65Yfc8Z3NVU0dbEvi+v+u0NQZxh2PIzU2uRY+91XacVeCWGoGzwNonONVprox7md4KSeiNvf2p5dxClf3wv14ceo1dKwTqNZHTzT0Muh51kGPB12wk9/X5gPuKRs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
