appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qDzZWBa36AsZ0M4ZtD+pi64W1nq6Q6iNvLI2JkqR+OezAGCr+yf1Rx38ijt6J/bKLF8+3GZKdWKUaMutUpb/SuxUOHOVQNqoCbquvfIBaFCubML3jQ24d5H80dQanJeX54VihHDPMUl+oP7cIibCdJsLvfwmUY5sbcsoPPqXLW/spakCgo//2ERd7wLnBH9oXGMEHdKn872cQdZ0mrZSB+2e9bpMb+w0fD5CgTtuAEMXAZE/rnUmhDnIEO195drWK/TD2IDgFKPa6h6FIFHEt8ND6R4Xk3ltQvn9JY4AbzcZaiR40KrMUwqyvmdXXUCb0/FGrhCFNUP7V2825cKh8l3zGklchJRhIRWXmTgTvy/Tgwb1Vkb0sy7sW4+54aaQ1wvZkRXa4KnyRRHa89ceoMTFKV/KTJtAdC/d8Z0ypjHYY6HNtuofjty+ypOL9T2iCQfQb5f3CWk4iNUgvfBbMzzOW5IcET0m7G6I071CXrcgXfD2c9PSoQyj6JpY0L2vygV/C6Q1TCldIpL9itiKiXe+pD1KXkKFUhRlBMy4bN3y+lQxai9DUF3ACuvztaOdwMLGCDh4CxDsTvGFAXdccTIA4Zm7ktY0Dvfs0BPM8u1N6h4vN8uMKLRBDoM8u63hzzH0vsb42yDHcZABPvVBKqNPXwnkqYHqfaUCziEYgWM=}
